import { Product } from './types';

export const products: Product[] = [
  {
    id: 1,
    slug: 'classic-denim-jacket',
    name: 'Classic Denim Jacket',
    description:
      'A timeless denim jacket that belongs in every wardrobe. Made from durable 100% cotton denim, this jacket features a classic point collar, button-front closure, and chest patch pockets. Perfect for layering over a t-shirt or hoodie.',
    price: 69.99,
    originalPrice: 89.99,
    images: ['jacket-1', 'jacket-2', 'jacket-3'],
    category: 'Outerwear',
    gender: 'Unisex',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Blue', 'Black'],
    reviews: [
      { id: 1, rating: 5, comment: 'Amazing quality and perfect fit!', author: 'Jane D.', date: '2023-05-15' },
      { id: 2, rating: 4, comment: 'A bit stiff at first, but softens up nicely.', author: 'John S.', date: '2023-05-20' },
    ],
    inventory: 50,
  },
  {
    id: 2,
    slug: 'slim-fit-stretch-jeans',
    name: 'Slim Fit Stretch Jeans',
    description:
      'Our most popular slim fit jeans, engineered for comfort and style. The stretch denim allows for easy movement while maintaining a sleek silhouette. Features a classic five-pocket design and a zip fly.',
    price: 79.5,
    images: ['jeans-1', 'jeans-2', 'jeans-3'],
    category: 'Bottoms',
    gender: 'Men',
    sizes: ['30x30', '32x32', '34x32', '36x34'],
    colors: ['Dark Wash', 'Light Wash', 'Black'],
    reviews: [
        { id: 3, rating: 5, comment: 'Best jeans I have ever owned.', author: 'Mike R.', date: '2023-06-01' },
    ],
    inventory: 100,
  },
  {
    id: 3,
    slug: 'organic-cotton-tee',
    name: 'Organic Cotton Tee',
    description:
      'A wardrobe essential, this t-shirt is crafted from ultra-soft 100% organic cotton. It has a classic crew neck and a comfortable, relaxed fit. Ideal for everyday wear, either on its own or as a base layer.',
    price: 25.0,
    images: ['tee-1', 'tee-2', 'tee-3'],
    category: 'Tops',
    gender: 'Unisex',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Heather Grey', 'Navy'],
    reviews: [
        { id: 4, rating: 5, comment: 'So soft and comfortable.', author: 'Emily P.', date: '2023-06-10' },
        { id: 5, rating: 5, comment: 'Great fit and holds up well in the wash.', author: 'Chris T.', date: '2023-06-12' },
    ],
    inventory: 200,
  },
  {
    id: 4,
    slug: 'floral-print-midi-dress',
    name: 'Floral Print Midi Dress',
    description:
      'Embrace sunny days with this beautiful floral midi dress. Made from a lightweight and breathable fabric, it features a flattering V-neck, short puff sleeves, and a flowy skirt. An elasticated waist ensures a comfortable fit.',
    price: 54.0,
    originalPrice: 68.0,
    images: ['dress-1', 'dress-2', 'dress-3'],
    category: 'Dresses',
    gender: 'Women',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Red Floral', 'Blue Floral'],
    reviews: [
        { id: 6, rating: 5, comment: 'Absolutely gorgeous dress! I get so many compliments.', author: 'Sarah L.', date: '2023-07-02' },
    ],
    inventory: 40,
  },
  {
    id: 5,
    slug: 'leather-ankle-boots',
    name: 'Leather Ankle Boots',
    description:
      'Step up your shoe game with these versatile leather ankle boots. Featuring a sleek design with a side zipper, a comfortable block heel, and a durable sole. Pairs perfectly with everything from jeans to dresses.',
    price: 120.0,
    images: ['boots-1', 'boots-2', 'boots-3'],
    category: 'Footwear',
    gender: 'Women',
    sizes: ['6', '7', '8', '9', '10'],
    colors: ['Black', 'Brown'],
    reviews: [
        { id: 7, rating: 4, comment: 'Stylish and comfy, but took a day to break in.', author: 'Jessica W.', date: '2023-08-11' },
    ],
    inventory: 60,
  },
  {
    id: 6,
    slug: 'canvas-tote-bag',
    name: 'Canvas Tote Bag',
    description:
      'Your new go-to bag for errands, beach days, and everything in between. This spacious tote is made from sturdy canvas and features an internal pocket for your keys and phone. The minimalist design makes it a versatile accessory.',
    price: 35.0,
    images: ['tote-1', 'tote-2'],
    category: 'Accessories',
    gender: 'Unisex',
    sizes: ['One Size'],
    colors: ['Natural', 'Olive'],
    reviews: [
      { id: 8, rating: 5, comment: 'So spacious and durable. I use it every day.', author: 'Alex G.', date: '2023-04-22' },
    ],
    inventory: 150,
  },
  {
    id: 7,
    slug: 'high-waisted-shorts',
    name: 'High-Waisted Shorts',
    description:
      'Classic high-waisted denim shorts for a vintage-inspired look. Features a flattering A-line silhouette, raw hem, and traditional five-pocket styling. Made from rigid denim that will mold to your body over time.',
    price: 49.99,
    originalPrice: 59.99,
    images: ['shorts-1', 'shorts-2', 'shorts-3'],
    category: 'Bottoms',
    gender: 'Women',
    sizes: ['24', '25', '26', '27', '28', '29', '30'],
    colors: ['Vintage Blue', 'Washed Black'],
    reviews: [
      { id: 9, rating: 5, comment: 'The perfect summer shorts!', author: 'Megan B.', date: '2023-07-18' },
    ],
    inventory: 80,
  },
  {
    id: 8,
    slug: 'button-down-flannel-shirt',
    name: 'Button-Down Flannel Shirt',
    description:
      'Stay cozy in this super-soft flannel shirt. It offers a relaxed fit, a classic plaid pattern, and a button-down front. Wear it open over a tee or buttoned up for a timeless, rugged look.',
    price: 65.0,
    images: ['flannel-1', 'flannel-2', 'flannel-3'],
    category: 'Tops',
    gender: 'Men',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Red Plaid', 'Green Plaid'],
    reviews: [
        { id: 10, rating: 5, comment: 'Incredibly soft and warm. Great for fall.', author: 'David K.', date: '2023-09-05' },
    ],
    inventory: 70,
  },
  {
    id: 9,
    slug: 'wool-beanie-hat',
    name: 'Wool Beanie Hat',
    description:
      'A soft, warm beanie made from a rich wool blend. Features a classic ribbed knit and a fold-over cuff. The perfect accessory to top off your cold-weather outfits.',
    price: 25.0,
    originalPrice: 30.0,
    images: ['beanie-1', 'beanie-2'],
    category: 'Accessories',
    gender: 'Unisex',
    sizes: ['One Size'],
    colors: ['Charcoal', 'Mustard', 'Forest Green'],
    reviews: [
      { id: 11, rating: 5, comment: 'Warm, stylish, and not itchy!', author: 'Olivia C.', date: '2023-10-01' },
    ],
    inventory: 120,
  },
  {
    id: 10,
    slug: 'minimalist-leather-sneakers',
    name: 'Minimalist Leather Sneakers',
    description:
      'Clean, simple, and incredibly versatile. These sneakers are made from premium leather with a durable rubber sole. The cushioned insole provides all-day comfort. Dress them up or down with ease.',
    price: 110.0,
    images: ['sneakers-1', 'sneakers-2', 'sneakers-3'],
    category: 'Footwear',
    gender: 'Unisex',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['White', 'Black'],
    reviews: [
      { id: 12, rating: 5, comment: 'My new favorite shoes. They go with everything.', author: 'Ben A.', date: '2023-08-25' },
    ],
    inventory: 90,
  },
  {
    id: 11,
    slug: 'classic-trench-coat',
    name: 'Classic Trench Coat',
    description: 'An iconic, water-resistant trench coat for timeless style. Perfect for layering in transitional weather, it features a double-breasted front, a removable belt, and adjustable cuff straps.',
    price: 150.00,
    images: ['trench-1', 'trench-2', 'trench-3'],
    category: 'Outerwear',
    gender: 'Women',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Beige', 'Navy'],
    reviews: [
      { id: 13, rating: 5, comment: 'A timeless piece. The quality is exceptional.', author: 'Sophia R.', date: '2023-10-15' },
    ],
    inventory: 50,
  },
  {
    id: 12,
    slug: 'chunky-knit-sweater',
    name: 'Chunky Knit Sweater',
    description: 'A cozy and stylish chunky knit sweater made from a soft wool blend. It features a relaxed fit, a classic crew neck, and ribbed trim. The perfect sweater for chilly days.',
    price: 85.00,
    originalPrice: 100.00,
    images: ['sweater-1', 'sweater-2', 'sweater-3'],
    category: 'Tops',
    gender: 'Unisex',
    sizes: ['S', 'M', 'L'],
    colors: ['Cream', 'Charcoal'],
    reviews: [
       { id: 14, rating: 5, comment: 'So warm and cozy, I never want to take it off!', author: 'Liam G.', date: '2023-11-02' },
    ],
    inventory: 80,
  },
  {
    id: 13,
    slug: 'silk-blend-scarf',
    name: 'Silk-Blend Scarf',
    description: 'An elegant scarf crafted from a luxurious silk and modal blend. Featuring a subtle print and eyelash fringe, it adds a touch of sophistication to any outfit.',
    price: 45.00,
    images: ['scarf-1', 'scarf-2'],
    category: 'Accessories',
    gender: 'Unisex',
    sizes: ['One Size'],
    colors: ['Pastel Pink', 'Light Blue'],
    reviews: [
      { id: 15, rating: 5, comment: 'Beautiful and so soft. It feels very luxurious.', author: 'Chloe T.', date: '2023-09-20' },
    ],
    inventory: 110,
  },
  {
    id: 14,
    slug: 'corduroy-pants',
    name: 'Corduroy Pants',
    description: 'Vintage-inspired corduroy pants with a modern straight-leg fit. Made from soft, fine-wale corduroy with a touch of stretch for comfort. A great alternative to jeans for a smart-casual look.',
    price: 75.00,
    images: ['corduroy-1', 'corduroy-2', 'corduroy-3'],
    category: 'Bottoms',
    gender: 'Men',
    sizes: ['30x32', '32x32', '34x32', '36x34'],
    colors: ['Caramel', 'Olive Green'],
    reviews: [
      { id: 16, rating: 4, comment: 'Great pants, very stylish. A bit snug at first.', author: 'Noah P.', date: '2023-10-25' },
    ],
    inventory: 65,
  }
];
